name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 */12 * * *"   # обновление каждые 12 часов
  workflow_dispatch:         # запуск вручную
  push:
    branches: [ main ]       # при пуше в main

permissions:
  contents: write            # даёт доступ к пушу в output

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ahmad2391778
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
